modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="random_items"
version="0.1.0"
displayName="Random Items"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="slitherskull200"
description='''
Adds OP copper items to 1.16.5 minecraft
'''

[[dependencies.random_items]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




